# Generated by Django 5.1.4 on 2024-12-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_first_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="driverslicense",
            old_name="owner_id",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="own",
            old_name="auto_id",
            new_name="auto",
        ),
        migrations.RenameField(
            model_name="own",
            old_name="owner_id",
            new_name="owner",
        ),
        migrations.AlterField(
            model_name="autoowner",
            name="date_of_birth",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="driverslicense",
            name="date_of_issue",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="own",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="own",
            name="start_date",
            field=models.DateField(),
        ),
    ]
