# Generated by Django 5.1.4 on 2024-12-14 00:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "project_first_app",
            "0002_rename_owner_id_driverslicense_owner_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Auto",
            new_name="Car",
        ),
        migrations.RenameModel(
            old_name="AutoOwner",
            new_name="Owner",
        ),
        migrations.RenameField(
            model_name="own",
            old_name="auto",
            new_name="car",
        ),
    ]
